eslint:
  version: 6.3.0
  enabled: true
  config_file: .eslintrc.yaml
  ignore_file: .eslintignore

jshint:
  enabled: false

sass-lint:
  enabled: true

scss:
  enabled: false

shellcheck:
  enabled: true
