language: node_js
notifications:
  email: false
os: linux
dist: bionic
matrix:
  fast_finish: true
  allow_failures:
  - node_js: 6
  - node_js: node
  - node_js: lts/*
node_js:
- 6
- 8
- 10
- 12
- lts/*
- node
before_deploy:
- git config --local user.name "$TRAVIS_AUTHOR_NAME"
- git config --local user.email "$TRAVIS_AUTHOR_EMAIL"
deploy:
  provider: script
  script: yarn lerna publish --conventional-commits --yes
  skip_cleanup: true
  on:
    branch: master
    node: 10
    os: linux
sudo: false
cache:
  yarn: true
  npm: false
  directories: [
    ".yarn/cache",
    "node_modules",
    "packages/android-icon-resize/node_modules",
    "packages/android-icons/node_modules",
    "packages/android-splash-generate/node_modules",
    "packages/android-splash/node_modules",
    "packages/asset-generator/node_modules",
    "packages/asset-service/node_modules",
    "packages/generic-icon-splash-generate/node_modules",
    "packages/ios-icon-resize/node_modules",
    "packages/ios-icons/node_modules",
    "packages/ios-splash-generate/node_modules",
    "packages/ios-splash/node_modules"
  ]
env:
  global:
  - secure: Ac/5lrXzjOgVAhgFov9gaP/7Y/E87lBke8s43qXnOHgtUM5X4QYcd+smc036vWIxPyFXxM923jylPI4gVvBLx2Dz1gEzcSQGbypoRa31opivB1etVwztku8h30izaOxGMzfa5bxx/ydwH5h+I4CIO5jXjCrtpMKseyZBEO8voRhw626pzkBo2PvgoOQfThpzItNQ0ZI5b1tqDDdQGQ18IWYNTY7MVhaTzFQUeJNJWRmWf6Fq/nwt1PuD4EpfpViirio+JVJYQE63cb35BSDOhinUSb76bFcYWMLU9M8BP6OV5xer833YtR7QkVqCII1AI/GJWubFi/JaviPwqi14RPSTnHXbvd6sagHZERfyaBmPNyLLxkVyYvg7tBqyimKUMCSs4IsGXPuVXY6E2S4JZzZWxUBPqehfv3yEkx4MefJ9KWUcXUU8qRjdT3YkJqaFTTF0Q81fUdU/e16JMYlxfwmIJm6u9gwABa1y4VrHKRQy6PbSCqDRiX4r1KafX7p/cHGlYAUvoXp29feY6J3W2G8UoXbyLhFj/v19CjKZwby19gNIU79MjIlnnOacXyNXVBlnuC/WEQIBDoQxp9nkc7V7xXnKtu+Ji65n0/IoDPCG+JM67gQTTIlGLXSJvMQ+lKJxleCUg4BkXPdGO5ox4PP2dUJG+vDGwKjTrF4+VHs=
  - secure: Zo4VUh0ViTUefECXN+oRyqmGqvwpT/HGeXfe5G4pMikxoJtqAZLskQldDExWfI9m0gzuzaVEYlzHXHg9cOoFpDw4liC5UgtTNnNyufoyMKhSaeJS0R2j9D7uNU8k9jE2FgcLaBPVA+YZQrrPGw/8Gzxrj5RVF00PY3/+dcbXQoD7mkUTWeh/UyCu8RugsThGsHrwaO4Okq0xkUA85oRofkOddGevXiclYqVmEt91ydDEmbIE9QlBxntmwLPI6IkGvts0QFkRCKeVId6kRD2KAxQTpcy4KrfSD7rOQhqWs6cH3uTWH2r/MW5aOJHriExz8Cycd8PenZwOJGZMVaxNUfAXmPbNw5+6vaOtvRb7yoc9R88YFwuHASQ5b6gHSGM5MO6CaUVglvmK8KD/gfUGuGGzz45eIKZv/x+KdHx8B1lI8b1q+TsZ9VWqrl7d4aN1L3biLdY6hJNxJHSSsBpTr4qWkrGNeMogqRkflu/gINZYAKkw72eAZ+HHely/Dwe7SKi8v9FXgCD8g4FUB8SvZWzT4Fz4K538VMHBgCLvAM1A8p0bLWEofzb2ZQCsYcEf+wfg7vZgIIHE3OoO3JrXCUNsBroZjzYNGryXwSlyBaTe32PqfQiJeMwJUambZ91l5Wjy1fPWAy4M2bdp8aH435ZBPj52FzHNqj582dJXZL4=
